![Numpy](img/numpy.png)

Bienvenue dans ce notebook d'initiation à **NumPy**, une bibliothèque essentielle pour la data science avec Python.

🎯 Objectif : Comprendre l'essentiel de NumPy

---

## 📌 Sommaire :
1. Création de tableaux
2. Dimensions et forme
3. Indexation & slicing
4. Opérations vectorielles
5. Fonctions statistiques
6. Manipulation et fusion
7. Broadcasting

---


# Introduction

NumPy (**Numerical Python**) est la bibliothèque de base pour le calcul scientifique avec Python. Elle permet de manipuler des structures de données puissantes appelées **arrays** ou **tableaux**, optimisées pour la performance et la simplicité d’usage. NumPy est utilisé par presque toutes les bibliothèques de l’écosystème <a href='https://pydata.org/'>PyData</a> (comme **Pandas**, **Scikit-learn**, **SciPy**) et constitue une compétence fondamentale pour tout data scientist ou ingénieur en machine learning.


<img src="img/numpy_foundation.png" alt="Numpy" style="display:block; margin-left:auto; margin-right:auto;">

**Pourquoi Numpy ?**

Contrairement aux listes Python classiques, les tableaux NumPy sont :
- Plus **rapides** et moins gourmands en mémoire
- Facilement extensibles à plusieurs dimensions (**vecteurs**, **matrices**, **tenseurs**)
- Compatibles avec des **opérations vectorisées** et du **broadcasting**
- Intégrés dans toutes les bibliothèques majeures de la **data science**

**Chargement de la librairie Numpy**

In [188]:
import numpy as np

# 1. 🎲 Création de tableaux NumPy

## 1.1. Depuis des objets Python

NumPy permet de créer facilement des tableaux numériques notamment à parti de listes Python

In [189]:
my_list = [5, 10, 15]           # liste Python contenant trois entiers
my_array = np.array(my_list)    # convertit cette liste en tableau numpy, ce qui permet ensuite d’appliquer des opérations vectorielles

display(my_list)
display(my_array)

[5, 10, 15]

array([ 5, 10, 15])

## 1.2. Tableaux 1D et 2D : vecteurs et matrices

La structure de base de NumPy est le `tableau` (array). Il peut être :

**1D** : vecteur

**2D** : matrice

ou **nD** (plusieurs dimensions)

In [190]:
# Vecteur 1D
v = np.array([1, 2, 3])

# Matrice 2D
m = np.array([[1, 2], [3, 4]])

display(type(v))
display(v)
print("---------------")
display(type(m))
display(m)

numpy.ndarray

array([1, 2, 3])

---------------


numpy.ndarray

array([[1, 2],
       [3, 4]])

🧠 **À retenir** : une matrice 2D peut contenir une seule ligne ou une seule colonne, mais reste bien en deux dimensions.

### 🧩 Exercices

> Créez et affichez un vecteur contenant les entiers de 10 à 20

In [191]:
vector = np.array([x for x in range(10, 21)])

vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

> Créez et affichez une matrice 3x3 avec les entiers de 1 à 9

In [192]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 1.3. Séquences numériques

Il est facile de générer facilement des suites de nombres avec Numpy.

In [193]:
sequence_1 = np.arange(0, 10, 2)    # crée une suite de nombres allant de 0 à 8 avec un pas de 2
sequence_2 = np.linspace(0, 1, 5)   # génère 5 valeurs également espacées entre 0 et 1 inclus

display(sequence_1)
display(sequence_2)

array([0, 2, 4, 6, 8])

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 🧩 Exercices

> Créez un tableau avec des valeurs entre 0 et 20 espacées de 5

In [194]:
my_array = np.arange(0, 21, 5)

my_array

array([ 0,  5, 10, 15, 20])

> Utilisez ``linspace`` pour créer un tableau de 50 valeurs entre -1 et 1

In [195]:
my_array = np.linspace(-1, 1, 50)

my_array

array([-1.        , -0.95918367, -0.91836735, -0.87755102, -0.83673469,
       -0.79591837, -0.75510204, -0.71428571, -0.67346939, -0.63265306,
       -0.59183673, -0.55102041, -0.51020408, -0.46938776, -0.42857143,
       -0.3877551 , -0.34693878, -0.30612245, -0.26530612, -0.2244898 ,
       -0.18367347, -0.14285714, -0.10204082, -0.06122449, -0.02040816,
        0.02040816,  0.06122449,  0.10204082,  0.14285714,  0.18367347,
        0.2244898 ,  0.26530612,  0.30612245,  0.34693878,  0.3877551 ,
        0.42857143,  0.46938776,  0.51020408,  0.55102041,  0.59183673,
        0.63265306,  0.67346939,  0.71428571,  0.75510204,  0.79591837,
        0.83673469,  0.87755102,  0.91836735,  0.95918367,  1.        ])

## 1.4. Génération de données aléatoires

NumPy propose également un module random pour créer des tableaux remplis de valeurs aléatoires.

In [196]:
# Entiers aléatoires (entre 0 et 10, exclu)
object_1 = np.random.randint(0, 10)           # un seul entier aléatoire entre 0 et 9
object_2 = np.random.randint(0, 10, (3, 3))   # matrice 3x3 d'entiers aléatoires entre 0 et 9

# Flottants aléatoires uniformes entre 0 et 1
object_3 = np.random.rand(4)                 # vecteur de 4 flottants tirés d'une distribution uniforme [0, 1)
object_4 = np.random.rand(4, 4)              # matrice 4x4 de flottants tirés d'une distribution uniforme [0, 1)

# Flottants aléatoires selon une loi normale (moyenne = 0, écart-type = 1)
object_5 = np.random.randn(4)                # vecteur de 4 flottants selon une loi normale centrée réduite
object_6 = np.random.randn(4, 4)             # matrice 4x4 de flottants selon une loi normale centrée réduite              

display(object_1)
display(object_2)
display(object_3)
display(object_4)
display(object_5)
display(object_6)

4

array([[1, 3, 3],
       [6, 9, 8],
       [6, 1, 8]])

array([0.27792804, 0.41386089, 0.02230611, 0.05893498])

array([[0.26902558, 0.67429704, 0.29179931, 0.64215673],
       [0.14471103, 0.05410838, 0.17021658, 0.81129392],
       [0.81501723, 0.36932116, 0.28925884, 0.62308942],
       [0.01350371, 0.45374602, 0.54092951, 0.81837492]])

array([ 0.43390441,  1.46000478,  0.72097432, -0.09691211])

array([[ 0.11298876, -0.99992618, -1.33078847, -0.75663349],
       [-1.40544271, -0.29914337,  1.05365798, -0.71787187],
       [ 1.09473064,  1.71582419, -0.59850801,  0.86106272],
       [-0.88105427, -0.37399702,  1.44433677,  1.28798937]])

### 🧩 Exercices

> Générez un entier aléatoire entre 1 et 100

In [197]:
random_int = np.random.randint(1, 101)

random_int

19

> Créez un tableau 1D de 10 entiers aléatoires entre 0 et 20

In [198]:
my_array = np.random.randint(0, 21, (10,))

my_array

array([ 7, 10,  5,  4,  8,  9, 10,  8, 10,  3])

> Générez une matrice 5x5 d’entiers entre 0 et 9

In [199]:
my_array = np.random.randint(0, 10, (5, 5))

my_array

array([[6, 8, 0, 9, 7],
       [0, 1, 7, 6, 3],
       [3, 1, 0, 9, 1],
       [2, 0, 0, 9, 0],
       [9, 7, 7, 1, 2]])

> Générez un vecteur de 6 flottants aléatoires entre 0 et 1

In [200]:
vector = np.random.rand(6)

vector

array([0.5282214 , 0.51459032, 0.07553137, 0.05800411, 0.12218124,
       0.83529601])

> Créez une matrice 3x3 de flottants aléatoires entre 0 et 1

In [201]:
matrix = np.random.rand(3, 3)

matrix

array([[0.40686537, 0.85267163, 0.64935992],
       [0.68957287, 0.83612493, 0.60932588],
       [0.04943167, 0.56343967, 0.81365145]])

> Générez un vecteur de 8 valeurs suivant une loi normale (moyenne 0, écart-type 1)

In [202]:
vector = np.random.randn(8)

vector

array([-1.85547727, -0.52904957, -0.079463  ,  0.25744721, -0.07812235,
        0.79708262, -0.16842516, -1.15336605])

> Créez une matrice 4x4 de valeurs aléatoires selon une loi normale

In [203]:
matrix = np.random.randn(4, 4)

matrix

array([[-0.73409478, -0.8887094 , -0.49496708,  0.69647688],
       [-1.00312962,  0.35979944,  1.57247839,  0.17489024],
       [ 0.78792663,  0.94493748, -1.04815757, -1.59097285],
       [ 0.22528892, -0.06652221, -0.33345509, -0.09763615]])

## 1.5. Tableaux pré-remplis

Numpy propose des fonctions pratiques pour créer rapidement des tableaux contenant des valeurs par défaut.

In [204]:
# Zéros
zeros = np.zeros(4)               # vecteur de 4 éléments contenant uniquement des zéros
zeros_matrix = np.zeros((4, 4))   # matrice 4x4 remplie de zéros

# Uns
ones = np.ones(4)                 # vecteur de 4 éléments contenant uniquement des uns
ones_matrix = np.ones((4, 4))     # matrice 4x4 remplie de uns

# Matrice identité 4x4 (matrice carrée avec des 1 sur la diagonale principale et des 0 ailleur.
# Elle joue un rôle similaire au nombre 1 pour la multiplication)
matrix_identity = np.eye(4)     


display(zeros)
display(zeros_matrix)

display(ones)
display(ones_matrix)

display(matrix_identity)

array([0., 0., 0., 0.])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([1., 1., 1., 1.])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 🧩 Exercices

> Créez un vecteur de 6 zéros

In [205]:
vector = np.zeros(6)

vector

array([0., 0., 0., 0., 0., 0.])

> Créez une matrice 3x5 remplie de zéros

In [206]:
matrix = np.zeros((3, 5))

matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

> Créez un vecteur de 10 uns

In [207]:
vector = np.ones(6)

vector

array([1., 1., 1., 1., 1., 1.])

> Créez une matrice 2x3 remplie de uns

In [208]:
matrix = np.ones((2, 3))

matrix

array([[1., 1., 1.],
       [1., 1., 1.]])

> Créez une matrice identité 8x8

In [209]:
matrix = np.eye(8, 8)

matrix

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

# 2. 📐 Dimensions et forme des tableaux

Numpy offre des attributs très utiles pour explorer la structure des tableaux

In [210]:
# Tableau de 0 à 11 transformé en matrice 3x4 grâce à la méthode .reshape()
# ⚠️ Attention : le produit des dimensions passées à reshape (ici 3×4 = 12) 
# doit exactement correspondre au nombre total d’éléments dans le tableau initial. Sinon, NumPy renverra une erreur !
array = np.arange(12).reshape(3, 4)        

print("Tableau :\n", array, "\n")                     # affiche le tableau
print("Forme (shape) :", array.shape, "\n")           # affiche la forme du tableau
print("Nombre de dimensions :", array.ndim, "\n")     # affiche le nombre de dimensions
print("Nombre total d'éléments :", array.size, "\n")  # affiche le nombre d'éléments
print("Type de données (dtype) :", array.dtype, "\n") # affiche le type des données

Tableau :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Forme (shape) : (3, 4) 

Nombre de dimensions : 2 

Nombre total d'éléments : 12 

Type de données (dtype) : int64 



### 🧩 Exercice

> Créez une matrice de forme 6x2 à partir de np.arange().  
> Affichez sa forme, son nombre d’éléments, son nombre de dimensions.

In [211]:
matrix = np.arange(12).reshape(6, 2)

display(matrix)
matrix.shape

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

(6, 2)

> Créez un tableau contenant les nombres de 0 à 19, puis transformez-le en matrice de 4 lignes et 5 colonnes.

In [212]:
my_array = np.arange(0, 20)
display(my_array)

matrix = my_array.reshape(4, 5)
display(matrix)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

> Vous disposez d’un tableau de 18 éléments. Quelles sont les trois formes possibles que vous pouvez lui donner avec reshape() en matrice 2D ?

In [213]:
# (3, 6)
# (6, 3)
# (9, 2)

# 3. 🔍 Indexing & Slicing

Lorsque vous travaillez avec des tableaux ou matrices NumPy, il est essentiel de savoir accéder aux éléments, **extraire des lignes**, **des colonnes** ou **des sous-parties**. Cette opération s’appelle l’**indexing** (accès à un ou plusieurs éléments) et le **slicing** (extraction de tranches).

NumPy utilise une syntaxe très proche de celle des listes Python, mais adaptée aux tableaux multidimensionnels. Grâce à cela, vous pouvez :
- Accéder à une valeur précise dans un tableau 2D
- Extraire une ligne ou une colonne
- Récupérer plusieurs lignes ou colonnes avec des tranches (slices)
- Utiliser des conditions (masques logiques) pour filtrer certains éléments

Dans les exemples suivants, nous allons manipuler une matrice 3x4 pour explorer ces différentes possibilités.

In [214]:
# Matrice de travail
matrix = np.arange(12).reshape(3, 4)

print("Matrice :\n", matrix)

Matrice :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 3.1. Indexing

**Indexing** = accès à un seul élément ou un groupe précis via des **indices explicites**.

In [215]:
print("Première ligne :", matrix[0])                # extrait toute la première ligne
print("Dernière ligne :", matrix[-1])               # extrait toute la dernière ligne
print("Première colonne :", matrix[:, 0])           # extrait tous les éléments de la 1ère colonne, sur toutes les lignes
print("Première colonne :", matrix[:, -1])          # extrait tous les éléments de la dernière colonne, sur toutes les lignes
print("Élément ligne 0, colonne 2 :", matrix[0, 2]) # extrait'élément situé à la 1ère ligne (index 0) et à la 3e colonne (index 2)

Première ligne : [0 1 2 3]
Dernière ligne : [ 8  9 10 11]
Première colonne : [0 4 8]
Première colonne : [ 3  7 11]
Élément ligne 0, colonne 2 : 2


## 3.2. Slicing

**Slicing** = accès à une plage continue d’éléments avec l’opérateur : `(start:stop:step)`.

In [216]:
print("Lignes 0 et 1 :\n", matrix[0:2], "\n")               # extrait les deux premières lignes (lignes 0 et 1 incluses, ligne 2 exclue)
print("Colonnes 1 et 2 :\n", matrix[:, 1:3], "\n")          # extrait toutes les lignes mais seulement les colonnes 1 et 2 (3 exclue)
print("Colonnes 0, 2, ... :\n", matrix[:, ::2], "\n")       # extrait toutes les lignes mais une colonne sur deux (colonne 0, 2...)
print("Éléments > 5 :\n", matrix[matrix > 5], "\n")         # extrait tous les éléments dont la valeur est strictement supérieure à 5
print("Éléments pairs :\n", matrix[matrix % 2 == 0], "\n")  # extrait tous les éléments qui sont des nombres pairs (reste = 0 quand divisé par 2)

Lignes 0 et 1 :
 [[0 1 2 3]
 [4 5 6 7]] 

Colonnes 1 et 2 :
 [[ 1  2]
 [ 5  6]
 [ 9 10]] 

Colonnes 0, 2, ... :
 [[ 0  2]
 [ 4  6]
 [ 8 10]] 

Éléments > 5 :
 [ 6  7  8  9 10 11] 

Éléments pairs :
 [ 0  2  4  6  8 10] 



### 🧩 Exercice

> À partir d’un tableau `array = np.arange(35).reshape(5, 7)`, répondez aux questions suivantes :  
> 1. Affichez l’élément situé à la 3e ligne et 5e colonne.  
> 2. Affichez toute la 2e ligne du tableau. 
> 3. Affichez toute la dernière colonne. 
> 4. Affichez les trois premières lignes du tableau. 
> 5. Affichez les colonnes 2 à 5 de toutes les lignes. 
> 6. Affichez les 3 derniers éléments de la 4e ligne.
> 7. Affichez une ligne sur deux (lignes 0, 2, 4).  
> 8. Affichez une colonne sur trois (colonnes 0, 3, 6).
> 9. Affichez tous les éléments strictement supérieurs à 25.
> 10. Affichez tous les éléments impairs du tableau.
> 11. Affichez tous les éléments compris entre 10 et 20 inclus.
> 12. Remplacez l’élément en ligne 1, colonne 4 par 999.
> 13. Remplacez tous les éléments multiples de 7 par -7.
> 14. Remplacez la 3e colonne par des zéros.

In [217]:
array = np.arange(35).reshape(5, 7)

print(array)

# 1. Élément à la 3e ligne et 5e colonne
print(array[2, 4])

# 2. Toute la 2e ligne
print(array[1])

# 3. Toute la dernière colonne
print(array[:, -1])

# 4. Les trois premières lignes
print(array[:3])

# 5. Colonnes 2 à 5 de toutes les lignes
print(array[:, 2:6])

# 6. Les 3 derniers éléments de la 4e ligne
print(array[3, -3:])

# 7. Une ligne sur deux
print(array[::2])

# 8. Une colonne sur trois
print(array[:, ::3])

# 9. Éléments strictement supérieurs à 25
print(array[array > 25])

# 10. Éléments impairs
print(array[array % 2 == 1])

# 11. Éléments entre 10 et 20 inclus
print(array[(array >= 10) & (array <= 20)])

# 12. Remplacer l’élément en ligne 1, colonne 4 par 999
array[1, 4] = 999
print(array)

# 13. Remplacer tous les multiples de 7 par -7
array[array % 7 == 0] = -7
print(array)

# 14. Remplacer la 3e colonne par des zéros
array[:, 2] = 0
print(array)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
18
[ 7  8  9 10 11 12 13]
[ 6 13 20 27 34]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[ 2  3  4  5]
 [ 9 10 11 12]
 [16 17 18 19]
 [23 24 25 26]
 [30 31 32 33]]
[25 26 27]
[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]
[[ 0  3  6]
 [ 7 10 13]
 [14 17 20]
 [21 24 27]
 [28 31 34]]
[26 27 28 29 30 31 32 33 34]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]
[10 11 12 13 14 15 16 17 18 19 20]
[[  0   1   2   3   4   5   6]
 [  7   8   9  10 999  12  13]
 [ 14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34]]
[[ -7   1   2   3   4   5   6]
 [ -7   8   9  10 999  12  13]
 [ -7  15  16  17  18  19  20]
 [ -7  22  23  24  25  26  27]
 [ -7  29  30  31  32  33  34]]
[[ -7   1   0   3   4   5   6]
 [ -7   8   0  10 999  12  13]
 [ -7  15   0  17  18  19  20]
 [ -7  22   0  24  2

# 4. ➕ Opérations vectorielles

Lorsqu’on travaille avec des tableaux NumPy (vecteurs ou matrices), on peut effectuer des opérations mathématiques directement sur l’ensemble des éléments, sans utiliser de boucles. On parle d’**opérations vectorielles** ou **opérations élément par élément**.

Cela permet :
- d’écrire du code plus simple et plus lisible,
- d’obtenir des calculs bien plus rapides grâce à l’optimisation interne de NumPy,
- de manipuler facilement des données numériques comme dans les domaines de la data science ou du machine learning.

**🤖 Pourquoi les opérations vectorielles sont essentielles en machine learning ?**

Dans le machine learning, on travaille en permanence avec :
- des vecteurs : chaque ligne de données (ex : un utilisateur avec ses caractéristiques) est un vecteur,
- des matrices : un ensemble de données (ex : tous les utilisateurs) forme une matrice,
- et des opérations mathématiques rapides pour entraîner et utiliser les modèles.


In [218]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print("Addition :", x + y)

print("Soustraction :", x - y)

print("Multiplication :", x * y)

print("Division :", y / x)

print("Carrés de x :", x ** 2)

print("Produit scalaire (x @ y) :", x @ y)
print("Produit scalaire (np.dot) :", np.dot(x, y))

print("Norme de x :", np.linalg.norm(x))

Addition : [11 22 33]
Soustraction : [ -9 -18 -27]
Multiplication : [10 40 90]
Division : [10. 10. 10.]
Carrés de x : [1 4 9]
Produit scalaire (x @ y) : 140
Produit scalaire (np.dot) : 140
Norme de x : 3.7416573867739413


### 🧩 Exercices

> Soit `x = np.array([2, 4, 6])` et `y = np.array([1, 3, 5])`  
> 1. Calculez x + y  
> 2. Calculez x - y  
> 3. Calculez x * y (multiplication élément par élément)  
> 4. Calculez x / y (division élément par élément)

In [219]:
x = np.array([2, 4, 6])
y = np.array([1, 3, 5])

print("x + y =", x + y)

print("x - y =", x - y)

print("x * y =", x * y)

print("x / y =", x / y)

x + y = [ 3  7 11]
x - y = [1 1 1]
x * y = [ 2 12 30]
x / y = [2.         1.33333333 1.2       ]


> Reprenez les vecteurs x et y ci-dessus  
> 1. Calculez le carré de chaque élément de x  
> 2. Calculez le double de chaque élément de y  
> 3. Ajoutez 10 à tous les éléments de x

In [220]:
print("x au carré :", x**2)

print("2 * y =", 2 * y)

print("x + 10 =", x + 10)

x au carré : [ 4 16 36]
2 * y = [ 2  6 10]
x + 10 = [12 14 16]


> Soit `x = np.array([1, 2, 3])` et `y = np.array([4, 5, 6])`  
> 1. Calculez le **produit scalaire** de x et y avec `@`  
> 2. Calculez le produit scalaire avec `np.dot()`  
> 3. Vérifiez que les deux résultats sont identiques

In [221]:
produit1 = x @ y
print("Produit scalaire avec @ :", produit1)

produit2 = np.dot(x, y)
print("Produit scalaire avec np.dot() :", produit2)

print("Les deux résultats sont-ils identiques ?", produit1 == produit2)

Produit scalaire avec @ : 44
Produit scalaire avec np.dot() : 44
Les deux résultats sont-ils identiques ? True


> Soit `v = np.array([3, 4])`  
> 1. Calculez la **norme** de v (indice : `np.linalg.norm`)  
> 2. Normalisez v (divisez chaque élément par la norme)  
> 3. Vérifiez que la norme du vecteur normalisé vaut 1

In [222]:
v = np.array([3, 4])

norme = np.linalg.norm(v)
print("Norme de v :", norme)

v_normalise = v / norme
print("Vecteur normalisé :", v_normalise)

print("Norme du vecteur normalisé :", np.linalg.norm(v_normalise))

Norme de v : 5.0
Vecteur normalisé : [0.6 0.8]
Norme du vecteur normalisé : 1.0


> Créez deux vecteurs a et b de taille 5, remplis avec des entiers de votre choix  
> 1. Faites la somme, la différence et le produit terme à terme  
> 2. Calculez la somme totale des éléments de a et de b  
> 3. Calculez la moyenne des éléments de a

In [223]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4, 6, 8, 10])

# 1. Opérations terme à terme
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)

# 2. Somme totale des éléments
print("Somme des éléments de a :", np.sum(a))
print("Somme des éléments de b :", np.sum(b))

# 3. Moyenne des éléments de a
print("Moyenne des éléments de a :", np.mean(a))

a + b = [ 3  7 11 15 19]
a - b = [-1 -1 -1 -1 -1]
a * b = [ 2 12 30 56 90]
Somme des éléments de a : 25
Somme des éléments de b : 30
Moyenne des éléments de a : 5.0


# 5. 📊 Fonctions statistiques utiles

NumPy propose de nombreuses fonctions pour analyser rapidement des données numériques : **maximum**, **minimum**, **moyenne**, **écart-type**, **somme**, etc. Ces fonctions permettent d’obtenir des indicateurs statistiques simples sur un tableau, qu’il soit 1D (vecteur) ou 2D (matrice).

## 5.1. Vecteur 1D

In [224]:
# Tableau de 10 entiers aléatoires entre 0 et 99
arr = np.random.randint(0, 100, (10,))

print("Tableau :", arr)
print("Max :", arr.max())                # Valeur maximale du tableau
print("Min :", arr.min())                # Valeur minimale du tableau
print("Moyenne :", arr.mean())           # Moyenne arithmétique
print("Écart-type :", arr.std())         # Écart-type (dispersion des valeurs)
print("Somme :", arr.sum())              # Somme de tous les éléments
print("Indice du max :", arr.argmax())   # Position (indice) de la valeur maximale
print("Indice du min :", arr.argmin())   # Position (indice) de la valeur minimale

Tableau : [97  6 97 77 51 49  2 11 46 69]
Max : 97
Min : 2
Moyenne : 50.5
Écart-type : 33.59240985699002
Somme : 505
Indice du max : 0
Indice du min : 6


## 5.2. Matrice 2D

In [225]:
# matrice 4x5 d'entiers aléatoires entre 0 et 99
matrix = np.random.randint(0, 100, (4, 5))

print("Matrice :\n", matrix, "\n")

print("Moyenne globale :", matrix.mean(), "\n")              # Moyenne de tous les éléments
print("Moyenne par ligne :", matrix.mean(axis=1), "\n")      # Moyenne de chaque ligne
print("Moyenne par colonne :", matrix.mean(axis=0), "\n")    # Moyenne de chaque colonne
print("Somme par colonne :", matrix.sum(axis=0), "\n")       # Somme de chaque colonne

Matrice :
 [[28 14 75 17 59]
 [10 91 19 63 87]
 [65 65 29 41 14]
 [14 31 73 79 23]] 

Moyenne globale : 44.85 

Moyenne par ligne : [38.6 54.  42.8 44. ] 

Moyenne par colonne : [29.25 50.25 49.   50.   45.75] 

Somme par colonne : [117 201 196 200 183] 



### 🧩 Exercices

> Générez un tableau de 15 entiers aléatoires entre 1 et 100.  
> Affichez la valeur maximale, la valeur minimale et leur écart.

In [226]:
my_array = np.random.randint(1, 101, (15,))
print("Tableau :", my_array)

max_val = np.max(my_array)
print("Valeur maximale :", max_val)

min_val = np.min(my_array)
print("Valeur minimale :", min_val)

print("Écart max - min :", max_val - min_val)

Tableau : [65 17 13 62 85 69  6 48 43 34 87 76 12 50 32]
Valeur maximale : 87
Valeur minimale : 6
Écart max - min : 81


> Générez un tableau de 20 entiers aléatoires entre 0 et 50.  
> Affichez la somme, la moyenne et la variance.

In [227]:
tableau = np.random.randint(0, 51, (20,))

print("Tableau :", tableau)

print("Somme :", np.sum(tableau))

print("Moyenne :", np.mean(tableau))

print("Variance :", np.var(tableau))

Tableau : [40 11 50 14 31  7 47  2  1  0 38 22 27 49 18 13 15 32 28 37]
Somme : 482
Moyenne : 24.1
Variance : 248.89000000000004


> Créez une matrice 5x4 d’entiers aléatoires entre 0 et 99.  
> Affichez la moyenne de chaque ligne et la moyenne de chaque colonne.

In [228]:
matrix = np.random.randint(0, 100, (5, 4))

print("Matrice :\n", matrix)

print("Moyenne par ligne :", np.mean(matrix, axis=1))

print("Moyenne par colonne :", np.mean(matrix, axis=0))

Matrice :
 [[12 99  0 21]
 [98 22 39 71]
 [12 85 39 95]
 [23 37 98 89]
 [38 17 69 16]]
Moyenne par ligne : [33.   57.5  57.75 61.75 35.  ]
Moyenne par colonne : [36.6 52.  49.  58.4]


> Générez une matrice 6x3 d'entiers aléatoires.  
> Affichez l’indice du maximum global, puis l’indice du maximum de chaque ligne.

In [229]:
matrix = np.random.randint(0, 100, (6, 3))

print(matrix)

print("Indice du maximum global (dans le tableau aplati) :", np.argmax(matrix))

print("Indice du maximum de chaque ligne :", np.argmax(matrix, axis=1))

[[ 2 33 74]
 [38 96 83]
 [98 94 65]
 [37 15 40]
 [31 14 32]
 [51 55 39]]
Indice du maximum global (dans le tableau aplati) : 6
Indice du maximum de chaque ligne : [2 1 0 2 2 1]


> Créez un tableau de 12 flottants aléatoires entre 0 et 1.  
> Comptez combien de valeurs sont supérieures à la moyenne.

In [230]:
my_array = np.random.rand(12)
print(my_array)

avg = np.mean(my_array)
print("Moyenne :", avg)

more_than_avg = np.sum(my_array > avg)
print("Nombre de valeurs supérieures à la moyenne :", more_than_avg)

[0.9020993  0.89056105 0.73456794 0.50507958 0.37632419 0.4998463
 0.11686054 0.90647303 0.52249013 0.4495012  0.4242959  0.52162842]
Moyenne : 0.5708106323046387
Nombre de valeurs supérieures à la moyenne : 4


> Générez un tableau de 50 entiers entre 10 et 100.  
> Calculez le 25e, le 50e (médiane) et le 75e percentile.

In [231]:
my_array = np.random.randint(10, 101, (50,))
print(my_array)

q1 = np.percentile(my_array, 25)
q2 = np.percentile(my_array, 50)
q3 = np.percentile(my_array, 75)

print("25e percentile :", q1)
print("50e percentile :", q2)
print("75e percentile :", q3)

[20 74 57 87 68 11 56 48 19 36 50 77 15 99 95 43 71 45 13 88 48 30 58 62
 80 41 67 55 79 80 93 30 48 26 60 17 10 65 75 64 93 62 51 15 60 48 98 80
 43 77]
25e percentile : 41.5
50e percentile : 57.5
75e percentile : 76.5


# 6. 🔧 Empilement et fusion de tableaux

Il est souvent nécessaire de combiner plusieurs tableaux NumPy pour former des structures plus grandes.  
Cela peut se faire en ajoutant des lignes (empilement vertical) ou des colonnes (empilement horizontal).

NumPy propose plusieurs fonctions pour cela :

- `np.vstack` : empilement dans le sens **vertical** (ajoute des lignes)
- `np.hstack` : empilement dans le sens **horizontal** (ajoute des colonnes)
- `np.concatenate` : fusion plus générale, où l’on choisit l’axe (`axis=0` pour les lignes, `axis=1` pour les colonnes)

⚠️ Pour que ces opérations fonctionnent, les **dimensions doivent être compatibles** :
- Pour empiler verticalement, les **nombres de colonnes doivent être identiques**
- Pour empiler horizontalement, les **nombres de lignes doivent être identiques**

In [232]:
a = np.array([[1, 2], [3, 4]])  # matrice 2x2
b = np.array([[5, 6]])          # matrice 1x2


# Empilement vertical : ajoute des lignes (mêmes nombres de colonnes requis)
vstacked = np.vstack([a, b])
print("Empilement vertical (vstack) :\n", vstacked, "\n")

# Empilement horizontal : ajoute des colonnes (mêmes nombres de lignes requis)
hstacked = np.hstack([a, a])
print("Empilement horizontal (hstack) :\n", hstacked, "\n")


# Fusion avec np.concatenate (plus général)
conc_v = np.concatenate([a, b], axis=0)  # même que vstack
print("Concaténation verticale :\n", conc_v, "\n")

conc_h = np.concatenate([a, a], axis=1)  # même que hstack
print("Concaténation horizontale :\n", conc_h, "\n")


# 💡 INFO :
# np.vstack([a, b]) et np.concatenate([a, b], axis=0) donnent exactement le même résultat :
# → ils empilent les tableaux verticalement (ajout de lignes).

# De même, np.hstack([a, a]) et np.concatenate([a, a], axis=1) sont aussi équivalents :
# → ils empilent les tableaux horizontalement (ajout de colonnes).

# ✅ vstack / hstack sont plus lisibles pour débuter,
# ✅ concatenate est plus flexible (surtout utile pour des tableaux à plus de 2 dimensions).

Empilement vertical (vstack) :
 [[1 2]
 [3 4]
 [5 6]] 

Empilement horizontal (hstack) :
 [[1 2 1 2]
 [3 4 3 4]] 

Concaténation verticale :
 [[1 2]
 [3 4]
 [5 6]] 

Concaténation horizontale :
 [[1 2 1 2]
 [3 4 3 4]] 



### 🧩 Exercices

> Créez deux matrices compatibles pour un empilement vertical :  
> - une matrice `a` de forme `(2, 3)`  
> - une matrice `b` de forme `(1, 3)`  
> - Utilisez `np.vstack()` pour les empiler.

In [233]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9]])

a_b = np.vstack([a, b])

a_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

> Reprenez les mêmes matrices que précdemment et utilisez np.concatenate() avec axis=0 pour vérifier qu’on obtient le même résultat qu’avec vstack.

In [234]:
a_concat_b = np.concatenate([a, b], axis=0)

a_concat_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

> Reprenez les mêmes matrices que précédemment et utilisez np.concatenate() avec axis=1 pour vérifier qu’on obtient le même résultat qu’avec hstack.

In [248]:
# Reprise de la matrice a
a = np.array([[1, 2, 3], [4, 5, 6]])

# Pour que l'empilement horizontal fonctionne, b doit avoir le même nombre de lignes que a
b = np.array([7, 8]).reshape(2, 1)  # forme (2, 1)

print(np.hstack((a, b)))
print(np.concatenate((a, b), axis=1))

[[1 2 3 7]
 [4 5 6 8]]
[[1 2 3 7]
 [4 5 6 8]]


# 7. 📡 Broadcasting (adaptation automatique des dimensions)

En NumPy, les opérations entre tableaux (addition, soustraction, etc.) nécessitent normalement que les formes (shape) soient **compatibles**.

Mais au lieu de lever une erreur quand les formes sont différentes, NumPy applique parfois automatiquement une règle intelligente d’adaptation des dimensions : c’est ce qu’on appelle le **broadcasting** (ou diffusion en français).

In [ ]:
A = np.array([[1], [2], [3]])  # Matrice de forme (3, 1) : vecteur colonne
B = np.array([10, 20, 30])     # Vecteur ligne de forme (3,)

print("A.shape =", A.shape, "\n")    # Affiche la forme de A : (3, 1)
print("B.shape =", B.shape, "\n")    # Affiche la forme de B : (3,)

# NumPy étend automatiquement A horizontalement (comme si on le copiait 3 fois en colonnes) pour l’aligner avec B (qui est traité comme une ligne).
# Résultat : addition élément par élément dans une matrice de forme (3, 3)
print("Résultat du broadcasting :\n", A + B)

### 🧩 Exercices

> Créez un vecteur `a = np.array([1, 2, 3])`.  
> Ajoutez le scalaire `5` à ce vecteur. Que se passe-t-il ?

In [241]:
a = np.array([1, 2, 3])

print(a)
print(a + 5)

[1 2 3]
[6 7 8]


> Créez une matrice `M` de forme (3, 4) avec `np.ones((3, 4))`.  
> Créez un vecteur `v = np.array([10, 20, 30, 40])`.  
> Faites `M + v` et observez le résultat.

In [244]:
M = np.ones((3, 4))
v = np.array([10, 20, 30, 40])

M + v

array([[11., 21., 31., 41.],
       [11., 21., 31., 41.],
       [11., 21., 31., 41.]])

> Créez une matrice `M = np.ones((3, 4))`.  
> Créez un vecteur colonne `v = np.array([[1], [2], [3]])`.  
> Faites `M + v`. Pourquoi cela fonctionne ?

In [247]:
M = np.ones((3, 4))
v = np.array([1, 2, 3]).reshape(3, 1)
M + v

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

> Créez `A = np.array([[1], [2], [3]])` (forme 3x1)  
> Créez `B = np.array([10, 20])` (forme 2,)  
> Essayez `A + B`. Que se passe-t-il ? Pourquoi ?

In [266]:
A = np.array([[1], [2], [3]])
B = np.array([10, 20]) 

A + B

# L'opération est OK grâce au broadcasting qui procède au reshape de chaque array pour les rendre compatibles

array([[11, 21],
       [12, 22],
       [13, 23]])

> Créez `X = np.ones((2, 3, 4))`  
> Créez `Y = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])` (forme 3x4)  
> Essayez `X + Y` et observez la forme du résultat.

In [ ]:
X = np.ones((2, 3, 4))
Y = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])

result = X + Y
print(result)
print(result.shape)

# Le résultat est une matrice 3D


[[[ 11.  21.  31.  41.]
  [ 51.  61.  71.  81.]
  [ 91. 101. 111. 121.]]

 [[ 11.  21.  31.  41.]
  [ 51.  61.  71.  81.]
  [ 91. 101. 111. 121.]]]
(2, 3, 4)


---
## ✅ Bravo !
Vous connaissez maintenant les bases essentielles de NumPy. Vous allez pouvoir aborder d'autres libriaries telles que **Pandas** ou **Scikit-learn**.